name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t victor140/ec-new .
      - name: Publish image to docker hub
        run: docker push victor140/ec-new:new

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull victor140/ec-new:new
      - name: Delete old container
        run: docker rm -f ec-new-container
      - name: Run docker container
        run: docker run -d -p 8082:8080 --name ec-new-container victor140/ec-new